# version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 4000:5000
    volumes: 
      - .:/usr/src/app
    environment:
      - CONNECTION_URL=${CONNECTION_URL}
      - PORT=${PORT}
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
